version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  # MongoDB administration tool - Mongoclient
  mongoclient:
    image: mongoclient/mongoclient
    # restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb_data:
